package app

import (
	"errors"
	"fmt"
	"os/exec"
	"strings"

	"github.com/nicodes/komizo/box"
	"github.com/nicodes/komizo/scripts"
)

// Re-running every app's setup script as part of `komizo update`.
//
// WHY THIS EXISTS. `komizo update` used to run the init script, install the
// agent and re-run the proxy -- and nothing else. The per-app scripts on the
// box (deploy-<app> and set-secret-<app>) are generated by scripts/alpine.sh,
// which only `komizo add` ran. So a fix to the DEPLOY SCRIPT reached no app
// that already existed: the operator upgraded, was told the box was up to date,
// and every app on it kept running last release's generated shell for as long
// as nobody happened to re-run `komizo add` per app.
//
// That is a rollout gap on its own. What made it urgent is that komizo ships
// the two halves of a pair down two different paths. The STOPPED marker WRITER
// is Go, compiled into the agent, so `komizo update` delivers it immediately;
// the marker READER is in the generated deploy script, so `komizo update`
// delivered nothing. On an updated box that combination gives you: `komizo
// stop` writes a durable STOPPED=1 record, the next CI deploy runs the OLD
// script which starts the app anyway, and box/diagnose.go keys app_down off the
// marker -- so an app that is up, and can go down, is filed as deliberately
// stopped and never pages again. Indefinitely, with nothing anywhere saying
// alerting had been switched off. komizo#57, komizo#58.
//
// The fix is the one update.go's own comment already promised: "ONE operation,
// re-running the whole setup rather than only replacing the agent binary [...]
// Every script it runs is safe to re-run." The per-app script is exactly a
// thing komizo puts on a box and versions with the rest of it, so it belongs in
// that sentence and was simply missing from the code under it.
//
// WHAT AN APP'S SETTINGS ARE, AND WHY THEY COME OFF THE BOX. An update is not
// an edit. It must reprovision each app with the values that app already has --
// its deploy account, its config image, its directory, the names CI dials it by
// -- because every one of them is something an operator chose and none of them
// is something this command was given. They are read back out of komizo's own
// record for the app (AppsDir/<name>.env), which is the file the state exists
// in; re-deriving them would be this command guessing, and two of the guesses
// are destructive. See appRefreshEnv for what each value would do if it were
// wrong.

// appRecord is one app on a box as komizo's own record describes it.
//
// The four fields are the four alpine.sh cannot work out for itself. Everything
// else it either derives from these or reads from the record itself -- KNOWN_AS
// most importantly, which is why there is no field for it here (see
// appRefreshEnv).
type appRecord struct {
	name   string // from the record's FILE NAME, which is what every reader uses
	user   string // CI_USER
	config string // CONFIG_IMAGE
	dir    string // APP_DIR
}

// appRecordsCmd prints one tab-separated line per app on the box.
//
// The apps are enumerated from komizo's own records rather than by globbing
// /srv, for the reason box/paths.go gives: an app placed elsewhere with
// --app-dir is invisible to that glob, and an app this command cannot see is an
// app that silently keeps the old deploy script -- i.e. the exact bug being
// fixed, narrowed to the apps least like the others.
//
// The app NAME comes from the file name and not from the APP_NAME line inside,
// because that is what alpine.sh, box/paths.go and the deploy script's own
// cross-app scan all key on. A record whose APP_NAME disagreed with its file
// name would otherwise have this command reprovision a different app.
//
// tr -d '\r' on every read for the reason the rest of komizo strips it: a
// record that picked up CRLF -- copied through an editor on another machine,
// restored from a backup taken on one -- reads back with a trailing CR that is
// invisible in a terminal. Left on, it fails check()'s charset test, so the app
// is refused and the update fails naming a value that looks perfectly correct
// in the file and in the error.
//
// The directory is a PARAMETER only so a test can run this loop for real
// against a directory it owns. appRecordsCmd is the one every box gets, built
// from box.AppsDir; TestTheEnumerationFindsEveryAppAndNothingElse asserts the
// two are the same command, so pointing the shipped one somewhere else fails
// there rather than leaving a test that proves things about a directory nothing
// reads. The value is spliced in unquoted because the glob has to expand, and
// box.AppsDir contains nothing a shell would treat specially.
func appRecordsCmdFor(dir string) string {
	return `for f in ` + dir + `/*.env; do
	[ -f "$f" ] || continue
	n="${f##*/}"; n="${n%.env}"
	printf '%s\t%s\t%s\t%s\n' "$n" \
		"$(sed -n 's/^CI_USER=//p' "$f" | tr -d '\r' | head -n 1)" \
		"$(sed -n 's/^CONFIG_IMAGE=//p' "$f" | tr -d '\r' | head -n 1)" \
		"$(sed -n 's/^APP_DIR=//p' "$f" | tr -d '\r' | head -n 1)"
done`
}

var appRecordsCmd = appRecordsCmdFor(box.AppsDir)

// appRecords asks the box which apps are on it.
//
// A box with no apps prints nothing and exits 0 -- the `[ -f "$f" ]` guard is
// what makes an unexpanded glob (no AppsDir at all, which is a box that has
// never had an app) indistinguishable from an empty one.
//
// THE FAILURE CARRIES THE BOX'S OWN WORDS. quiet() suppresses stderr, which is
// right for a probe whose failure is an expected answer -- and this is the
// opposite of one. If this step fails, no app on the box is refreshed, and
// "exit status 1" on its own leaves an operator with a command that silently
// did nothing and no way to find out why. exec.Cmd.Output fills ExitError.Stderr
// for exactly this, so the reason is put back in.
func (t target) appRecords() ([]appRecord, error) {
	out, err := t.quiet(appRecordsCmd)
	if err != nil {
		return nil, appListError(err)
	}
	return parseAppRecords(out), nil
}

// appListError puts the box's own words back on a failure quiet() swallowed.
// Its own function so it can be tested: the branch only runs on a box that has
// gone wrong, which is the branch nobody exercises and the one whose whole job
// is to be readable.
func appListError(err error) error {
	var ee *exec.ExitError
	if errors.As(err, &ee) && len(ee.Stderr) > 0 {
		return fmt.Errorf("could not read the list of apps on this box: %w\n    %s",
			err, strings.TrimSpace(string(ee.Stderr)))
	}
	return fmt.Errorf("could not read the list of apps on this box: %w", err)
}

func parseAppRecords(out string) []appRecord {
	var recs []appRecord
	for _, ln := range strings.Split(out, "\n") {
		// SplitN rather than Split, so a value that somehow contains a tab
		// lands in the last field instead of making the line one field too
		// long. A line dropped here is an app nobody hears about, and an app
		// nobody hears about is precisely the silence this file exists to
		// remove -- so the only lines dropped are ones with too FEW fields
		// (the empty output of a box with no apps, or anything else that is
		// not a line this command printed). Everything else survives to be
		// refused, out loud, by check().
		f := strings.SplitN(ln, "\t", 4)
		if len(f) != 4 {
			continue
		}
		recs = append(recs, appRecord{
			name:   strings.TrimSpace(f[0]),
			user:   strings.TrimSpace(f[1]),
			config: strings.TrimSpace(f[2]),
			dir:    strings.TrimSpace(f[3]),
		})
	}
	return recs
}

// check refuses to reprovision an app whose record does not fully describe it.
//
// SKIPPING IS THE SAFE ANSWER HERE, and defaulting is not. alpine.sh fills in
// its own defaults for a value it is not given -- CI_USER becomes
// komizo-<app>, APP_DIR becomes /srv/<app> -- and both defaults are actively
// dangerous applied to an app that chose otherwise:
//
//   - a missing CI_USER would make the script believe the app had been RENAMED
//     onto a new account, and its OLD_CI_USER path then deletes the previous
//     account, its key file, its doas rule and its sshd block. An app deploying
//     under an explicit --user would stop being deployable at all, from an
//     operation the operator was told was a routine upgrade.
//   - a missing APP_DIR would point the regenerated deploy script at
//     /srv/<app>, so the next deploy would write compose.yml somewhere the app
//     does not live and start nothing, while reporting success.
//
// A record that cannot answer is a record something else has already broken, so
// the honest move is to leave that app alone and say so loudly. refreshApps
// counts a skip as a failure for exactly that reason: an app silently not
// refreshed is the bug this whole file exists to remove.
//
// NO MESSAGE HERE NAMES A FLAG. Every validator below is written for `komizo
// add`, where there is a --user or a --config to be wrong about, and `komizo
// update` passes neither -- so the wrapped text is deliberately dropped rather
// than carried through with %w. Told "--app-dir contains characters that are
// not allowed", an operator goes looking for a flag they did not type while the
// record that is actually wrong goes unmentioned; the file and the key are what
// they can act on, so those are what these say. Review 1 caught this leaking
// through the malformed cases after the missing ones had been fixed.
func (r appRecord) check() error {
	// The name comes from the file name, so a name that is not an app name means
	// the FILE is not one of komizo's. Said that way round, because "blog.old.env"
	// left beside a record is somebody's backup and not a broken app -- and the
	// rest of komizo reads it as an app too (box/paths.go enumerates every *.env),
	// so it is worth hearing about rather than skipping in silence.
	if validateApp(r.name) != nil {
		return fmt.Errorf("%q is not a name komizo gives an app, so %s is not a record "+
			"komizo wrote -- move it out of that directory if it is a backup",
			r.name, box.AppsDir+"/"+r.name+".env")
	}
	if r.user == "" {
		return fmt.Errorf("its record names no CI_USER, so komizo does not know which account deploys it")
	}
	if validateUser(r.user) != nil {
		return fmt.Errorf("its record's CI_USER is %q, which is not a name an account can have "+
			"(letters, digits, underscore and hyphen only)", r.user)
	}
	if r.config == "" {
		return fmt.Errorf("its record names no CONFIG_IMAGE, so komizo does not know what it deploys from")
	}
	if validateConfigImage(r.config) != nil {
		return fmt.Errorf("its record's CONFIG_IMAGE is %q, which is not a registry path with no tag "+
			"-- the tag is chosen per deploy, so one recorded here would pin every deploy to it", r.config)
	}
	if r.dir == "" {
		return fmt.Errorf("its record names no APP_DIR, so komizo does not know where it lives")
	}
	if validateAppDir(r.dir) != nil {
		return fmt.Errorf("its record's APP_DIR is %q, which is not an absolute path komizo will act on", r.dir)
	}
	return nil
}

// appRefreshEnv is the environment one app's re-run of alpine.sh gets, and
// every entry in it is load-bearing. This is the whole difference between "the
// box was upgraded" and "the box was reconfigured".
//
//   - CI_PUBKEY EMPTY means "leave the deploy key alone". alpine.sh writes the
//     account's authorized_keys file wholesale, so a key generated here would
//     REPLACE the one the repo's GitHub secret holds -- every app on the box
//     would stop deploying the moment somebody ran an update, with the failure
//     appearing in CI hours later and nothing connecting it to the upgrade.
//     Empty is also why an app whose account has no key at all fails this step
//     rather than silently getting one: alpine.sh refuses, which is correct.
//
//   - KNOWN_AS EMPTY plus CLEAR_KNOWN_AS=0 means "not mentioned", which
//     alpine.sh reads as "keep what is recorded". An update is not saying the
//     names CI dials this app by have changed, so it must not say anything
//     about them. Passing CLEAR_KNOWN_AS=1 would erase them, and known_hosts is
//     matched on the exact name dialled -- so the next deploy would fail host
//     key verification on a name that had worked for months.
//
//   - HARDEN_SSH=0 because whether root may log in with a password is a policy
//     decision about the WHOLE MACHINE and not something an upgrade gets to
//     take. alpine.sh only removes its global block when it is about to rewrite
//     it, so 0 leaves hardening a previous run applied exactly as it is: this
//     neither imposes nor undoes.
//
//   - CI_USER, CONFIG_IMAGE and APP_DIR carried verbatim from the record, for
//     the reasons check() spells out.
//
// STOPPED, STOPPED_AT and STOPPED_BY are DELIBERATELY ABSENT, and their absence
// is what preserves them. alpine.sh reads the existing record and carries the
// stop across its own rewrite (komizo#48); there is no input that sets one and
// no input that clears one, so an update cannot express an opinion about
// whether an app should be running. It must not: clearing a deliberate stop
// during an upgrade would be a worse version of the bug this change fixes --
// the app comes back up, nobody asked for it, and the report agrees with the
// containers so nothing looks wrong.
func appRefreshEnv(r appRecord) map[string]string {
	return map[string]string{
		"APP_NAME":       r.name,
		"CI_USER":        r.user,
		"CONFIG_IMAGE":   r.config,
		"APP_DIR":        r.dir,
		"CI_PUBKEY":      "",
		"KNOWN_AS":       "",
		"CLEAR_KNOWN_AS": "0",
		"HARDEN_SSH":     "0",
	}
}

// refreshBoxApps is the whole of what an update owes the apps on a box: ask the
// box which apps it has, then re-run each one's setup.
//
// ONE function, called from both surfaces, because the failure this file exists
// to fix is exactly the failure of a capability existing on one path and not the
// other. `komizo update` and the interface's `u` are the same operation, and
// the previous version of that promise -- update.go's comment about re-running
// the whole setup -- was true of the comment and not of either caller.
//
// BOTH HALVES ARE PARAMETERS, and that is a testing decision taken on purpose.
// This function is the seam: everything above it is a surface and everything
// below it is logic, so a version of it that quietly did nothing would restore
// the exact behaviour this change removes while every test that enters below it
// stayed green. That mutant was live until Review 1 found it. Now the listing
// and the running are both injectable, so the seam itself has a test.
func refreshBoxApps(list func() ([]appRecord, error), out progress,
	runner func(script string, env map[string]string) error) error {
	recs, err := list()
	if err != nil {
		return err
	}
	return refreshApps(recs, out, runner)
}

// refreshApps re-runs the setup script for every app on the box.
//
// ONE FAILURE DOES NOT STOP THE REST. A box with five apps and one broken
// record should end the update with four refreshed apps and a sentence naming
// the fifth, not with one refreshed app and four still carrying the old deploy
// script. But the command still FAILS at the end: an app that was not
// refreshed is an app running whatever it ran before, which after this change
// is the one state nobody is watching for any more.
//
// The runner is a parameter for the reason performAdd's is -- the command line
// streams to a terminal and the interface streams into its run pane, and having
// the two differ only there is what keeps `komizo update` and the interface's
// `u` one implementation instead of two that drift apart. It is also what lets
// this be tested without a server.
func refreshApps(recs []appRecord, out progress, runner func(script string, env map[string]string) error) error {
	if len(recs) == 0 {
		out.note("no apps on this box, so there are no deploy scripts to refresh.")
		return nil
	}
	var failed []string
	for _, r := range recs {
		out.step("Refreshing %s", r.name)
		if err := r.check(); err != nil {
			out.note("skipped %s: %v", r.name, err)
			failed = append(failed, r.name)
			continue
		}
		if err := runner(scripts.AlpineScript, appRefreshEnv(r)); err != nil {
			// The script's own messages are written for the hand-run case it
			// documents -- "pass as $1 or CI_PUBKEY" and the like -- and nobody
			// running an update passed either. Said here rather than left to be
			// puzzled over, because the likeliest cause by far is a key file
			// that is missing, and the reflex it invites (rotate the key) is the
			// one thing an update deliberately never does.
			out.note("could not refresh %s -- see the output above. komizo update passes no", r.name)
			out.note("flags of its own, so a message naming one is describing that app's record.")
			failed = append(failed, r.name)
			continue
		}
	}
	if len(failed) > 0 {
		return fmt.Errorf("the rest of the box is updated, but these apps still carry the\n"+
			"    deploy script they had before, so fixes to it have not reached them: %s.\n"+
			"\n"+
			"    That is the pairing komizo#58 is about, and it applies to those apps now:\n"+
			"    the agent on this box writes a durable stop marker, their deploy scripts\n"+
			"    do not read one, so `komizo stop` on any of them will look like it worked\n"+
			"    and the next deploy will start it again with the marker still set -- at\n"+
			"    which point it stops paging. Run 'komizo add' for each once the reason\n"+
			"    above is dealt with, or leave them running until you have.",
			strings.Join(failed, ", "))
	}
	return nil
}
