#!/bin/sh
# cli/scripts/alpine-proxy.sh - installs the one shared reverse proxy, as root.
#
# komizo embeds this and pipes it over SSH. To read it: `komizo script proxy`.
#
# One Caddy container per server terminates TLS and owns ports 80 and 443.
# It holds NO per-app configuration of its own. Its Caddyfile is three lines
# and never changes:
#
#     import /etc/caddy/routes/*.caddy
#
# One file per app, generated by deploy-<app> from the hostnames that app
# declared. So adding, changing or removing an app never edits anything shared
# -- which is the property that lets apps stay independent on a box they share.
#
# The routes live with the PROXY, at /srv/_proxy/routes, and that directory is
# the only thing mounted into the container. They used to live beside each app
# at /srv/<app>/caddy, which meant the proxy had to mount the whole of /srv to
# resolve its import glob -- and every app's secrets.env, 600 and root-owned,
# was then readable by the one process on this box that faces the internet.
# Read-only was never the protection it looked like: the risk was reading.
#
# Deliberately NOT label-based discovery (caddy-docker-proxy): that needs the
# docker socket inside the container listening on the public internet, and the
# socket is root. This design gives the proxy no privileges at all -- it reads
# one directory of generated routes and cannot talk to the daemon.
#
# Safe to re-run: that is how you update Caddy or move it to another network.
#
# Certificates need no configuration at all. Caddy agrees to the CA's terms
# when it runs non-interactively, and there is deliberately no contact address
# to set: Let's Encrypt stopped sending expiry notices in June 2025, so an email
# here would buy nothing but a field to fill in.
#
# Inputs, all environment variables:
#   SHARED_NETWORK docker network apps join                 (default: edge)
#   PROXY_IMAGE    caddy image to run                       (default: caddy:2)
#   TLS_ASK        on-demand-TLS gate URL                   (default: none)

set -eu

SHARED_NETWORK="${SHARED_NETWORK:-edge}"
PROXY_IMAGE="${PROXY_IMAGE:-caddy:2}"
TLS_ASK="${TLS_ASK:-}"

# The leading underscore is reserved: komizo refuses to create an app whose name
# starts with one, so this can never collide with /srv/<app>.
API_SOCKET_DIR="${API_SOCKET_DIR:-/run/komizo/api}"
mkdir -p "$API_SOCKET_DIR"

PROXY_DIR=/srv/_proxy
# One generated route per app, plus the catch-all below. The only part of the
# host filesystem the proxy container can see.
ROUTES_DIR="$PROXY_DIR/routes"
# Compose project names must start with a letter or digit, so the project cannot
# simply be named after the directory. Fixed rather than derived so the deploy
# and remove scripts can address the container without discovering it.
PROXY_PROJECT=komizo-proxy
PROXY_CONTAINER=komizo-proxy

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root"

case "$SHARED_NETWORK" in
	''|*[!A-Za-z0-9._-]*) die "SHARED_NETWORK must be letters, digits, dot, underscore or hyphen" ;;
esac
case "$PROXY_IMAGE" in
	*[!A-Za-z0-9.:/_-]*) die "PROXY_IMAGE contains characters that are not valid in an image reference" ;;
esac
# Interpolated into the Caddyfile, so it is constrained rather than trusted.
case "$TLS_ASK" in
	'') ;;
	http://*|https://*)
		case "$TLS_ASK" in
			*[!A-Za-z0-9.:/_?=~%\&-]*) die "TLS_ASK contains characters that are not valid in a URL" ;;
		esac ;;
	*) die "TLS_ASK must be an http:// or https:// URL" ;;
esac
command -v docker >/dev/null 2>&1 || die "this server is not set up yet -- run 'komizo init' first"

# --- 1. the shared network -------------------------------------------------
# Created here rather than by compose so it outlives any single project, and so
# an app can join it as `external: true` before the proxy is ever started.

if docker network inspect "$SHARED_NETWORK" >/dev/null 2>&1; then
	log "Shared network '$SHARED_NETWORK' already exists"
else
	log "Creating shared network '$SHARED_NETWORK'"
	docker network create "$SHARED_NETWORK" >/dev/null
fi

# --- 2. the Caddyfile ------------------------------------------------------

log "Writing $PROXY_DIR/Caddyfile"
mkdir -p "$ROUTES_DIR" "$PROXY_DIR/logs"
chown root:root "$PROXY_DIR" "$ROUTES_DIR" "$PROXY_DIR/logs"
chmod 755 "$PROXY_DIR" "$ROUTES_DIR"
# Access logs. 750 rather than 755: they carry client IPs and request paths,
# which is the one thing on this box that is about the people using it rather
# than about the box.
chmod 750 "$PROXY_DIR/logs"

{
	printf '# Written by komizo. Re-run "komizo proxy" to change it.\n'
	printf '#\n'
	printf '# This file terminates TLS and hands each hostname to the app that\n'
	printf '# claimed it. It routes; it does not configure anybody. What an app\n'
	printf '# does with a request once it arrives is inside that app, in its own\n'
	printf '# gate container, and cannot be written from here or broken from\n'
	printf '# here.\n'

	# On-demand TLS is the one global option, and it belongs to the SERVER
	# rather than to an app: it decides, for the whole box, who is allowed to
	# make it request certificates. An app used to ship this block in its own
	# config image, which made every app on the machine share one namespace
	# where Caddy permits exactly one such block -- so a second app adding one
	# took the box down.
	# No blank line before the global block: 'caddy fmt' removes one, and a
	# config that is not formatted the way Caddy formats it warns on every
	# reload -- which trains you to ignore reload warnings.
	if [ -n "$TLS_ASK" ]; then
		printf '{\n'
		printf '\t# Certificates for wildcard hostnames are issued on demand, one per\n'
		printf '\t# name. Without a gate, anyone who pointed a DNS record at this box\n'
		printf '\t# could make it request certificates on their behalf -- so an app is\n'
		printf '\t# asked whether a hostname is real. Set with: komizo proxy --tls-ask\n'
		printf '\ton_demand_tls {\n'
		printf '\t\task %s\n' "$TLS_ASK"
		printf '\t}\n'
		printf '}\n'
	fi

	printf '\n# One file per app, written by deploy-<app> from the hostnames that\n'
	printf '# app published. Nothing here names an app, so adding or removing one\n'
	printf '# never edits shared config.\n'
	printf '#\n'
	printf '# This directory is the whole of what this container can see of the\n'
	printf '# host. It holds generated routes and nothing else -- no app config,\n'
	printf '# no secrets, no compose files.\n'
	printf 'import /etc/caddy/routes/*.caddy\n'
} > "$PROXY_DIR/Caddyfile"
chown root:root "$PROXY_DIR/Caddyfile"
chmod 644 "$PROXY_DIR/Caddyfile"

# A catch-all for hostnames that resolve here but have no app behind them: they
# get a plain 404 instead of whichever app Caddy happens to list first.
#
# It lives in the routes directory alongside the generated ones. The leading
# underscore cannot collide with an app's file: komizo refuses to create an app
# whose name starts with one. Caddy matches the most specific site address
# regardless of file order, so a bare ":80" here never shadows a real hostname.
cat > "$ROUTES_DIR/_catchall.caddy" <<'EOF'
# Written by komizo. Requests for a hostname with no app behind it land here.
:80 {
	# LOGGED, because this is where a scan shows up.
	#
	# `log` is a per-SITE-BLOCK directive; the global `log` option configures
	# Caddy's runtime log and there is no global switch for access logs. So a
	# site block without this one records nothing, which is what this block did
	# -- and it is the block whose whole subject is requests nobody expected.
	# A hostname pointed at this box with no app behind it, a probe of the
	# catch-all, a misdirected DNS record: none of it left a trace.
	#
	# Same shape and same bound as the per-app routes alpine.sh writes, so a
	# reader comparing two route files finds one answer rather than two.
	# box/access.go parses this JSON and reads only the last 4MB of it.
	#
	# NOT `log_credentials`. Caddy redacts Authorization, Proxy-Authorization,
	# Cookie and Set-Cookie by default, and that global option is what turns the
	# redaction OFF. Somebody debugging a token problem is exactly who would
	# reach for it, and it would write device tokens for somebody's server to
	# disk on that server.
	log {
		output file /var/log/caddy/access.log {
			roll_size 10mb
			roll_keep 3
		}
		format json
	}
	respond "no app is configured for this hostname" 404
}
EOF
chown root:root "$ROUTES_DIR/_catchall.caddy"
chmod 644 "$ROUTES_DIR/_catchall.caddy"

# --- 3. the container ------------------------------------------------------

log "Writing $PROXY_DIR/compose.yml"
cat > "$PROXY_DIR/compose.yml" <<EOF
# Written by komizo. Re-run 'komizo proxy' to change it; edits here are lost.
services:
  # Named for what it is, not what it runs. A compose service name is a network
  # alias, and this one sits on the network every app's gate joins -- so a
  # service called "caddy" claimed that name box-wide, which is precisely what
  # this proxy tells apps not to do. It answered to both "caddy" and its
  # container name; now only the latter.
  komizo-proxy:
    image: $PROXY_IMAGE
    container_name: $PROXY_CONTAINER
    restart: unless-stopped
    # This is the one process on the box facing the internet, so give it the
    # least it can run with. Drop every Linux capability and add back only the
    # one it needs to bind 80/443, forbid privilege escalation, and run on a
    # read-only root filesystem -- everything Caddy writes (certificates, its
    # config store, access logs) is a named volume or the tmpfs below.
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
    # The only container on this box that publishes a port. Apps are reached
    # over the '$SHARED_NETWORK' network by name, so they publish nothing.
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PROXY_DIR/Caddyfile:/etc/caddy/Caddyfile:ro
      # The generated routes, and NOTHING else of the host.
      #
      # This used to be the whole of /srv, read-only, so the import glob could
      # be written in host paths. Read-only stopped a compromised proxy writing
      # an app's compose.yml -- but it could still READ every app's
      # secrets.env, which is 600 root and therefore wide open to a container
      # running as root. The one process on this box exposed to the internet
      # had every production credential on it a file read away.
      #
      # Now it sees generated route files, which komizo wrote and which contain
      # nothing but hostnames and an upstream.
      - $ROUTES_DIR:/etc/caddy/routes:ro
      # The one writable path. Access logs are written here rather than to
      # stdout so that the proxy's own log -- the one that explains a
      # certificate failure -- does not become a request firehose, and so the
      # host can total them up by reading a file rather than by asking docker.
      #
      # Named explicitly rather than making /srv writable: this is the only
      # thing the proxy has any business writing.
      - $PROXY_DIR/logs:/var/log/caddy:rw
      # The socket komizo's own read API answers on, when this box has one.
      #
      # A DIRECTORY with nothing in it but that socket, and writable because
      # connecting to a unix socket needs write permission on it. Mounting
      # /run/komizo instead would have been simpler and would have handed the
      # one internet-facing container on this box a writable path beside
      # report.json.
      #
      # Bind-mounted whether or not the box serves itself: an empty directory
      # costs nothing, and a mount that appears only sometimes is a proxy that
      # has to be recreated the day somebody enrols.
      - $API_SOCKET_DIR:$API_SOCKET_DIR:rw
      # ACME account key and issued certificates. Losing this volume means
      # every certificate is re-issued, and Let's Encrypt rate limits are per
      # domain per week -- so it is the one volume on the box worth backing up.
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared
    # Unbounded by default, which is a disk filling up slowly enough that
    # nobody notices until it has. This is Caddy's RUNTIME log -- TLS renewals,
    # ACME, startup. The access log is a separate file under the logs volume,
    # written by a per-site-block `log` directive in each generated route, and
    # it rotates itself.
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  caddy_data:
  caddy_config:

networks:
  shared:
    external: true
    name: $SHARED_NETWORK
EOF
chown root:root "$PROXY_DIR/compose.yml"
chmod 644 "$PROXY_DIR/compose.yml"

log "Starting the proxy"
cd "$PROXY_DIR"
docker compose -p "$PROXY_PROJECT" config -q \
	|| die "the generated proxy compose.yml is not valid -- nothing was started"
# --remove-orphans matters on a rename: the container under the old service name
# keeps running and keeps holding 80 and 443, so the new one cannot bind and the
# box serves nothing at all.
docker compose -p "$PROXY_PROJECT" up -d --remove-orphans

# Report what Caddy made of it. A fragment that fails to parse keeps the proxy
# on its previous config rather than taking the site down, so a silent failure
# here would otherwise look like a working deploy.
if ! docker exec "$PROXY_CONTAINER" caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
	printf '\n'
	printf 'warning: Caddy is running, but the combined config does not validate.\n' >&2
	printf 'One of the generated routes under %s is malformed:\n' "$ROUTES_DIR" >&2
	docker exec "$PROXY_CONTAINER" caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile 2>&1 | sed 's/^/  /' >&2 || true
fi

log "Done"
cat <<EOF

  proxy:    $PROXY_CONTAINER ($PROXY_IMAGE)
  dir:      $PROXY_DIR (root-owned)
  network:  $SHARED_NETWORK
  certs:    ${PROXY_PROJECT}_caddy_data (docker volume -- back this up)

EOF

cat <<EOF
For an app to be reachable through it, that app needs two things.

A gate container -- its own Caddy, nginx, or anything that speaks HTTP --
named <app>-gate, listening on :80, joined to '$SHARED_NETWORK', publishing
no ports of its own:

  services:
    myapp-gate:
      image: ghcr.io/you/myapp-gate:\${APP_VERSION}
      networks:
        shared: {}
        default: {}
  networks:
    shared:
      external: true
      name: $SHARED_NETWORK

Only the gate joins the shared network. Everything behind it -- the API, the
database -- stays on the app's own 'default' network, where no other app on this
box can reach it.

And a hostnames file in the app's config image, one name per line:

  myapp.example.com
  www.myapp.example.com

That is all this proxy is told. It generates the route itself and points every
one of those names at myapp-gate:80, so no app writes config this server
loads, and no app's mistake can be another app's outage.

Everything a request meets after the hostname match -- paths, headers, static
files, which service answers what -- is inside the gate image the app built.
EOF
